[package]
name = "day7"
version = "0.1.0"
authors = ["David Wilemski <david@wilemski.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path = "../intcode" }
itertools = { version = "0.8"}
